CREATE TYPE datatype AS ENUM (
    'quantity',
    'quality-score'
);

CREATE TABLE journal_settings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER REFERENCES users(id),
    metric TEXT NOT NULL UNIQUE, 
    description TEXT NOT NULL, 
    type datatype NOT NULL
);